sudo: false
language: generic

before_install:

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER_NAME=gcc CXX=g++-7 CC=g++-7
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER_NAME=gcc CXX=g++-5 CC=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - libc++-dev
      env:
        - COMPILER_NAME=clang CXX=clang++-3.6 CC=clang++-3.6
        - CPLOPT=-stdlib=libc++
script:
  - ./gtest_build.sh
  - ./gradlew build
